[workspace]
authors = ["ARC345 <arnavrastogi.543@gmail.com>"]
channels = ["conda-forge"]
name = "tailor"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-frontend = "npm install"
dev = "npm run tauri:dev"
build = "npm run tauri:build"
sidecar = "python sidecar/main.py"
test = "pytest sidecar/tests"
[dependencies]
python = ">=3.14.2,<3.15"
nodejs = ">=25.2.1,<25.3"
langchain = ">=1.2.3,<2"
langchain-openai = ">=1.1.7,<2"
websockets = ">=15.0.1,<16"
loguru = ">=0.7.3,<0.8"
python-dotenv = ">=1.2.1,<2"
langgraph = ">=1.0.5,<2"
pytest = ">=9.0.2,<10"
pytest-asyncio = ">=1.3.0,<2"
pytest-cov = ">=7.0.0,<8"
pytest-mock = ">=3.15.1,<4"
